Update patch set 4
Patch Set 4: Code-Review-1

frameworks/base/services/java/com/android/server/wm/WindowManagerService.java:834: error: method getUiContext() is already defined in class WindowManagerService
    private Context getUiContext() {
                    ^
make: *** [/root/android/omni/out/target/common/obj/APPS/SystemUI_intermediates/classes-full-debug.jar] Błąd 41
make: *** Oczekiwanie na niezakończone zadania....
Note: frameworks/testing/uiautomator/library/core-src/com/android/uiautomator/core/UiScrollable.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Warning: AndroidManifest.xml already defines versionCode (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines versionName (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines minSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines targetSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.
frameworks/base/services/java/com/android/server/pm/PackageManagerService.java:6732: error: method sendBroadcast in class PackageRemovedInfo cannot be applied to given types;
        info.sendBroadcast(false, false, false);
            ^
  required: boolean,boolean,boolean,boolean
  found: boolean,boolean,boolean
  reason: actual and formal argument lists differ in length

Patch-set: 4
Label: Code-Review=-1