Update patch set 7
Patch Set 7: Code-Review-1

Breaks build.
frameworks/base/policy/src/com/android/internal/policy/impl/PhoneWindowManager.java:600: cannot find symbol
symbol  : variable EXPANDED_DESKTOP_STATE
location: class android.provider.Settings.System
                    Settings.System.EXPANDED_DESKTOP_STATE), false, this,
                                   ^
frameworks/base/policy/src/com/android/internal/policy/impl/PhoneWindowManager.java:603: cannot find symbol
symbol  : variable EXPANDED_DESKTOP_STYLE
location: class android.provider.Settings.System
                    Settings.System.EXPANDED_DESKTOP_STYLE), false, this,
                                   ^
frameworks/base/policy/src/com/android/internal/policy/impl/PhoneWindowManager.java:1409: cannot find symbol
symbol  : variable EXPANDED_DESKTOP_STYLE
location: class android.provider.Settings.System
                    Settings.System.EXPANDED_DESKTOP_STYLE, 0, UserHandle.USER_CURRENT);
                                   ^
frameworks/base/policy/src/com/android/internal/policy/impl/PhoneWindowManager.java:1411: cannot find symbol
symbol  : variable EXPANDED_DESKTOP_STATE
location: class android.provider.Settings.System
                        Settings.System.EXPANDED_DESKTOP_STATE, 0, UserHandle.USER_CURRENT) == 0) {

Patch-set: 7