Update patch set 2
Patch Set 2:

This also requires reverting of https://github.com/omnirom/android_frameworks_native/commit/282b7b9d03e863dab95d4ae037e67b4533afdfc9 but I can't push it on gerrit.

error: unpack failed: error Missing tree 661eb0d95ecc642b8e8745de1a5516e95a6e0907
fatal: Unpack error, check server log

Looks like server problem (did clean repo sync from scratch on my side)

Patch-set: 2