Update patch set 4
Patch Set 4:

Looks like this caused a build error on my end. Reverted and building again...

ERROR: frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/phone/PhoneStatusBarPolicy.java:249: stat_sys_ringer_silent cannot be resolved or is not a field

Patch-set: 4
Reviewer: Gerrit User 1001243 <1001243@56841c99-7c94-43d4-bf0b-cb4707e66d55>
Label: Code-Review=0