Fix: Error in frameworks/base while building for CAF variants
1. I am not sure whether a previous fix has been propsed by anyone regarding this error.
2. This is a minor change in the flag.

The following is the error caused by the existing flag:
frameworks/base/core/jni/android_view_Surface.cpp:206:14: error: 'class android::Surface' has no member named 'setDirtyRect'
     surface->setDirtyRect(&rect);

Change-Id: I9ff11314e1629ab0a7f3b34e9c571d78ce683a19
Signed-off-by: ramsudharsan <ramsudharsanm@gmail.com>