Update patch set 26
Patch Set 26: Code-Review-1

Needs rebased, it breaks builds with latest source?
frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/phone/QuickSettingsModel.java:1268: cannot find symbol
symbol  : method locationMode()
location: class com.android.systemui.statusbar.policy.LocationController
        mLocationState.iconId = getLocationDrawableMode(mLocationController.locationMode());

Patch-set: 26
Reviewer: Gerrit User 1000448 <1000448@56841c99-7c94-43d4-bf0b-cb4707e66d55>
Label: Code-Review=-1