Update patch set 6
Patch Set 6: Code-Review-1

/root/android/omni/out/target/common/obj/JAVA_LIBRARIES/framework-base_intermediates/src/core/java/com/android/internal/app/IAssetRedirectionManager.java:181: cannot find symbol
symbol  : class PackageRedirectionMap
location: package android.content.res
public android.content.res.PackageRedirectionMap getPackageRedirectionMap(java.lang.String themePackageName, java.lang.String themeId, java.lang.String targetPackageName) throws android.os.RemoteException;
                          ^
/root/android/omni/out/target/common/obj/JAVA_LIBRARIES/framework-base_intermediates/src/core/java/com/android/internal/app/IAssetRedirectionManager.java:110: cannot find symbol
symbol  : class PackageRedirectionMap
location: package android.content.res
@Override public android.content.res.PackageRedirectionMap getPackageRedirectionMap(java.lang.String themePackageName, java.lang.String themeId, java.lang.String targetPackageName) throws android.os.RemoteException
                                    ^
/root/android/omni/out/target/common/obj/JAVA_LIBRARIES/framework-base_intermediates/src/core/java/com/android/internal/app/IAssetRedirectionManager.java:57: cannot find symbol
symbol  : class PackageRedirectionMap
location: package android.content.res
android.content.res.PackageRedirectionMap _result = this.getPackageRedirectionMap(_arg0, _arg1, _arg2);
                   ^
/root/android/omni/out/target/common/obj/JAVA_LIBRARIES/framework-base_intermediates/src/core/java/com/android/internal/app/IAssetRedirectionManager.java:114: cannot find symbol
symbol  : class PackageRedirectionMap
location: package android.content.res
android.content.res.PackageRedirectionMap _result;
                   ^
/root/android/omni/out/target/common/obj/JAVA_LIBRARIES/framework-base_intermediates/src/core/java/com/android/internal/app/IAssetRedirectionManager.java:123: package android.content.res.PackageRedirectionMap does not exist
_result = android.content.res.PackageRedirectionMap.CREATOR.createFromParcel(_reply);

Patch-set: 6