telephony: Add back fake getHandlerExecutor()
Needed for IZAT for eg or all others old packages.

Removed in 958f200876fb4e3a3e8335f06dbdf08c295ea58f

03-17 12:51:24.495 26599 26616 E AndroidRuntime: FATAL EXCEPTION: IZatServiceContext
03-17 12:51:24.495 26599 26616 E AndroidRuntime: Process: com.qualcomm.location, PID: 26599
03-17 12:51:24.495 26599 26616 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getHandlerExecutor()Lcom/android/internal/telephony/util/HandlerExecutor; in class Landroid/telephony/SubscriptionManager$OnSubscriptionsChangedListener; or its super classes (declaration of 'android.telephony.SubscriptionManager$OnSubscriptionsChangedListener' appears in /system/framework/framework.jar!classes3.dex)

Change-Id: I06e8caf39056dba0979d65d822e56a0cc11591e2